version: "3.8"

services:
  portfolio:
    build:
      context: .
    container_name: portfolio
    restart: unless-stopped
    networks:
      - thrx_portfolio
    environment:
      - NODE_ENV=production

networks:
  thrx_portfolio:
    external: true
